FROM node:24-alpine AS build

WORKDIR /usr/src/app

COPY . .
RUN npm ci

ENV VITE_BACKEND_URL=/api

RUN npm run build

FROM nginx:1.29-alpine

COPY --from=build /usr/src/app/dist /usr/share/nginx/html
