services:
  app:
    image: todo-front
    build:
      context: . # The context will pick this directory as the "build context"
      args:
        VITE_BACKEND_URL: /api
    container_name: todo-front # This will name the container hello-front-dev
